steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
    - './app' # Path to your Dockerfile and application code
  id: Build

# Step 2: Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
  id: Push

# Step 3: Deploy the image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gcloud'
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
    - '--region=${_LOCATION}'
    - '--platform=managed'
    - '--allow-unauthenticated' # Adjust based on your security needs
  id: Deploy
  env:
    - 'PROJECT_ID=$PROJECT_ID'

images:
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: flask-app
  _AR_REPO_NAME: flask-app-repo
  _LOCATION: us-central1 # e.g., us-central1
